
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},k;for(k in g)g.hasOwnProperty(k)&&(aa[k]=g[k]);var ba=[],ca="./this.program";function da(a,b){throw b;}var ea=!1,l=!1,fa=!1,ha=!1;ea="object"===typeof window;l="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!l;var q="",ia,ja,ka,la;
if(fa)q=l?require("path").dirname(q)+"/":__dirname+"/",ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);return ka.readFileSync(a,b?null:"utf8")},ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),ba=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ma))throw a;}),process.on("unhandledRejection",
r),da=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ba=scriptArgs:"undefined"!=typeof arguments&&(ba=arguments),"function"===typeof quit&&(da=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||l)l?q=self.location.href:document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},l&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var na=g.print||console.log.bind(console),u=g.printErr||console.warn.bind(console);for(k in aa)aa.hasOwnProperty(k)&&(g[k]=aa[k]);aa=null;g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var oa;g.wasmBinary&&(oa=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&u("no native wasm support detected");var pa,qa=new WebAssembly.Table({initial:642,maximum:642,element:"anyfunc"}),ra=!1;
function assert(a,b){a||r("Assertion failed: "+b)}function sa(a){if("number"===typeof a){var b=!0;var c=a}else b=!1,c=a.length;var d=w(Math.max(c,1));if(b){a=d;assert(0==(d&3));for(b=d+(c&-4);a<b;a+=4)x[a>>2]=0;for(b=d+c;a<b;)A[a++>>0]=0;return d}a.subarray||a.slice?B.set(a,d):B.set(new Uint8Array(a),d);return d}var ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?ua(B,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);h=65536+((h&1023)<<10)|n&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function wa(a){var b=va(a)+1,c=xa(b);E(a,A,c,b);return c}var ya,A,B,za,Aa,x,F,G,Ba,Ca=g.INITIAL_MEMORY||16777216;g.wasmMemory?pa=g.wasmMemory:pa=new WebAssembly.Memory({initial:Ca/65536,maximum:Ca/65536});pa&&(ya=pa.buffer);Ca=ya.byteLength;var H=ya;ya=H;g.HEAP8=A=new Int8Array(H);g.HEAP16=za=new Int16Array(H);
g.HEAP32=x=new Int32Array(H);g.HEAPU8=B=new Uint8Array(H);g.HEAPU16=Aa=new Uint16Array(H);g.HEAPU32=F=new Uint32Array(H);g.HEAPF32=G=new Float32Array(H);g.HEAPF64=Ba=new Float64Array(H);x[37080]=5391360;function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Dd;"number"===typeof c?void 0===b.ed?g.dynCall_v(c):g.dynCall_vi(c,b.ed):c(void 0===b.ed?null:b.ed)}}}var Ea=[],Fa=[],Ga=[],Ha=[],Ia=[];function Ja(){var a=g.preRun.shift();Ea.unshift(a)}
var Ka=Math.abs,La=Math.ceil,Ma=Math.floor,Na=Math.min,Oa=0,Pa=null,Qa=null;g.preloadedImages={};g.preloadedAudios={};function r(a){if(g.onAbort)g.onAbort(a);na(a);u(a);ra=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ra(a){var b=Sa;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ta(){return Ra("data:application/octet-stream;base64,")}var Sa="QuadraticApproximation.wasm";
if(!Ta()){var Ua=Sa;Sa=g.locateFile?g.locateFile(Ua,q):q+Ua}function Va(){try{if(oa)return new Uint8Array(oa);if(ja)return ja(Sa);throw"both async and sync fetching of the wasm failed";}catch(a){r(a)}}function Wa(){return oa||!ea&&!l||"function"!==typeof fetch||Ra("file://")?new Promise(function(a){a(Va())}):fetch(Sa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Sa+"'";return a.arrayBuffer()}).catch(function(){return Va()})}
var Xa,Ya,$a={8692:function(){var a=g.keyboardListeningElement||document;return a===document?1:a===window?2:"id"in a?sa(Za(a.id)):0},9313:function(a){a:for(var b="";;){var c=B[a++>>0];if(!c)break a;b+=String.fromCharCode(c)}document.getElementById("canvas").style.cursor=b},9383:function(a,b){function c(){var d=window.requestAnimationFrame(c),e=[b];(e&&e.length?g.dynCall_ii.apply(null,[a].concat(e)):g.dynCall_ii.call(null,a))||window.cancelAnimationFrame(d)}window.requestAnimationFrame(c)},118419:function(a){a=
C(a);return"undefined"!==typeof process&&a in process.env?sa(Za(process.env[a])):0}};Fa.push({Dd:function(){ab()}});function bb(){return 0<bb.Vc}function cb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function db(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=cb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function eb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function fb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function gb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=cb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var hb=[];function ib(a,b){hb[a]={input:[],output:[],Pc:b};jb(a,kb)}
var kb={open:function(a){var b=hb[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Pc.flush(a.tty)},flush:function(a){a.tty.Pc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Pc.td)throw new I(60);for(var e=0,f=0;f<d;f++){try{var h=a.tty.Pc.td(a.tty)}catch(n){throw new I(29);}if(void 0===h&&0===e)throw new I(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Pc.ld)throw new I(60);
try{for(var e=0;e<d;e++)a.tty.Pc.ld(a.tty,b[c+e])}catch(f){throw new I(29);}d&&(a.node.timestamp=Date.now());return e}},lb={td:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.Vc?Buffer.Vc(256):new Buffer(256),d=0;try{d=ka.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Za(b,!0)}return a.input.shift()},ld:function(a,b){null===b||10===b?(na(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(na(ua(a.output,0)),a.output=[])}},mb={ld:function(a,b){null===b||10===b?(u(ua(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(u(ua(a.output,0)),a.output=[])}},K={Gc:null,Jc:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);K.Gc||(K.Gc={dir:{node:{Lc:K.Dc.Lc,Hc:K.Dc.Hc,lookup:K.Dc.lookup,Yc:K.Dc.Yc,rename:K.Dc.rename,unlink:K.Dc.unlink,rmdir:K.Dc.rmdir,readdir:K.Dc.readdir,symlink:K.Dc.symlink},stream:{Nc:K.Cc.Nc}},file:{node:{Lc:K.Dc.Lc,Hc:K.Dc.Hc},stream:{Nc:K.Cc.Nc,read:K.Cc.read,write:K.Cc.write,nd:K.Cc.nd,wd:K.Cc.wd,$c:K.Cc.$c}},link:{node:{Lc:K.Dc.Lc,Hc:K.Dc.Hc,readlink:K.Dc.readlink},stream:{}},od:{node:{Lc:K.Dc.Lc,
Hc:K.Dc.Hc},stream:nb}});c=ob(a,b,c,d);16384===(c.mode&61440)?(c.Dc=K.Gc.dir.node,c.Cc=K.Gc.dir.stream,c.Bc={}):32768===(c.mode&61440)?(c.Dc=K.Gc.file.node,c.Cc=K.Gc.file.stream,c.Ec=0,c.Bc=null):40960===(c.mode&61440)?(c.Dc=K.Gc.link.node,c.Cc=K.Gc.link.stream):8192===(c.mode&61440)&&(c.Dc=K.Gc.od.node,c.Cc=K.Gc.od.stream);c.timestamp=Date.now();a&&(a.Bc[b]=c);return c},Ud:function(a){if(a.Bc&&a.Bc.subarray){for(var b=[],c=0;c<a.Ec;++c)b.push(a.Bc[c]);return b}return a.Bc},Vd:function(a){return a.Bc?
a.Bc.subarray?a.Bc.subarray(0,a.Ec):new Uint8Array(a.Bc):new Uint8Array(0)},qd:function(a,b){var c=a.Bc?a.Bc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Bc,a.Bc=new Uint8Array(b),0<a.Ec&&a.Bc.set(c.subarray(0,a.Ec),0))},Jd:function(a,b){if(a.Ec!=b)if(0==b)a.Bc=null,a.Ec=0;else{if(!a.Bc||a.Bc.subarray){var c=a.Bc;a.Bc=new Uint8Array(b);c&&a.Bc.set(c.subarray(0,Math.min(b,a.Ec)))}else if(a.Bc||(a.Bc=[]),a.Bc.length>b)a.Bc.length=b;else for(;a.Bc.length<b;)a.Bc.push(0);
a.Ec=b}},Dc:{Lc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ec:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Bd=4096;b.blocks=Math.ceil(b.size/b.Bd);return b},Hc:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&K.Jd(a,b.size)},lookup:function(){throw pb[44];},Yc:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=qb(b,c)}catch(f){}if(d)for(var e in d.Bc)throw new I(55);}delete a.parent.Bc[a.name];a.name=c;b.Bc[c]=a;a.parent=b},unlink:function(a,b){delete a.Bc[b]},rmdir:function(a,b){var c=qb(a,b),d;for(d in c.Bc)throw new I(55);delete a.Bc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Bc)a.Bc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},Cc:{read:function(a,b,c,d,e){var f=a.node.Bc;if(e>=a.node.Ec)return 0;a=Math.min(a.node.Ec-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Bc||a.Bc.subarray)){if(f)return a.Bc=b.subarray(c,c+d),a.Ec=d;if(0===a.Ec&&0===e)return a.Bc=
b.slice(c,c+d),a.Ec=d;if(e+d<=a.Ec)return a.Bc.set(b.subarray(c,c+d),e),d}K.qd(a,e+d);if(a.Bc.subarray&&b.subarray)a.Bc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Bc[e+f]=b[c+f];a.Ec=Math.max(a.Ec,e+d);return d},Nc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ec);if(0>b)throw new I(28);return b},nd:function(a,b,c){K.qd(a.node,b+c);a.node.Ec=Math.max(a.node.Ec,b+c)},wd:function(a,b,c,d,e,f){assert(0===b);if(32768!==(a.node.mode&61440))throw new I(43);a=a.node.Bc;
if(f&2||a.buffer!==ya){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=w(c);if(!c)throw new I(48);A.set(a,c)}else d=!1,c=a.byteOffset;return{be:c,Ad:d}},$c:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new I(43);if(e&2)return 0;K.Cc.write(a,b,0,d,c,!1);return 0}}},rb=null,sb={},tb=[],ub=1,vb=null,wb=!0,xb={},I=null,pb={};
function L(a,b){a=gb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={sd:!0,md:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.md)throw new I(32);a=cb(a.split("/").filter(function(h){return!!h}),!1);var e=rb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=qb(e,a[d]);c=db(c+"/"+a[d]);e.Zc&&(!f||f&&b.sd)&&(e=e.Zc.root);if(!f||b.hd)for(f=0;40960===(e.mode&61440);)if(e=yb(c),c=gb(eb(c),e),e=L(c,{md:b.md}).node,40<f++)throw new I(32);}return{path:c,node:e}}
function zb(a){for(var b;;){if(a===a.parent)return a=a.Jc.xd,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%vb.length}function qb(a,b){var c;if(c=(c=Bb(a,"x"))?c:a.Dc.lookup?0:2)throw new I(c,a);for(c=vb[Ab(a.id,b)];c;c=c.Id){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Dc.lookup(a,b)}
function ob(a,b,c,d){a=new Cb(a,b,c,d);b=Ab(a.parent.id,a.name);a.Id=vb[b];return vb[b]=a}var Db={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Eb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Bb(a,b){if(wb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Fb(a,b){try{return qb(a,b),20}catch(c){}return Bb(a,"wx")}function Gb(a){var b=4096;for(a=a||0;a<=b;a++)if(!tb[a])return a;throw new I(33);}function Hb(a,b){Ib||(Ib=function(){},Ib.prototype={});var c=new Ib,d;for(d in a)c[d]=a[d];a=c;b=Gb(b);a.fd=b;return tb[b]=a}var nb={open:function(a){a.Cc=sb[a.node.rdev].Cc;a.Cc.open&&a.Cc.open(a)},Nc:function(){throw new I(70);}};function jb(a,b){sb[a]={Cc:b}}
function Jb(a,b){var c="/"===b,d=!b;if(c&&rb)throw new I(10);if(!c&&!d){var e=L(b,{sd:!1});b=e.path;e=e.node;if(e.Zc)throw new I(10);if(16384!==(e.mode&61440))throw new I(54);}b={type:a,Zd:{},xd:b,Hd:[]};a=a.Jc(b);a.Jc=b;b.root=a;c?rb=a:e&&(e.Zc=b,e.Jc&&e.Jc.Hd.push(b))}function Kb(a,b,c){var d=L(a,{parent:!0}).node;a=fb(a);if(!a||"."===a||".."===a)throw new I(28);var e=Fb(d,a);if(e)throw new I(e);if(!d.Dc.Yc)throw new I(63);return d.Dc.Yc(d,a,b,c)}function M(a){Kb(a,16895,0)}
function Lb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Kb(a,b|8192,c)}function Mb(a,b){if(!gb(a))throw new I(44);var c=L(b,{parent:!0}).node;if(!c)throw new I(44);b=fb(b);var d=Fb(c,b);if(d)throw new I(d);if(!c.Dc.symlink)throw new I(63);c.Dc.symlink(c,b,a)}function yb(a){a=L(a).node;if(!a)throw new I(44);if(!a.Dc.readlink)throw new I(28);return gb(zb(a.parent),a.Dc.readlink(a))}
function Nb(a,b,c,d){if(""===a)throw new I(44);if("string"===typeof b){var e=Db[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=db(a);try{f=L(a,{hd:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(f){if(b&128)throw new I(20);}else f=Kb(a,c,0),e=!0;if(!f)throw new I(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new I(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Eb(b)||b&512)?31:Bb(f,Eb(b)):44))throw new I(c);if(b&512){c=f;var h;"string"===typeof c?h=L(c,{hd:!0}).node:h=c;if(!h.Dc.Hc)throw new I(63);if(16384===(h.mode&61440))throw new I(31);if(32768!==(h.mode&61440))throw new I(28);if(c=Bb(h,"w"))throw new I(c);h.Dc.Hc(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Hb({node:f,path:zb(f),flags:b,seekable:!0,position:0,Cc:f.Cc,Pd:[],error:!1},d);d.Cc.open&&d.Cc.open(d);!g.logReadFiles||b&1||(Ob||(Ob={}),a in Ob||(Ob[a]=1,u("FS.trackingDelegate error on read file: "+
a)));try{xb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),xb.onOpenFile(a,f))}catch(n){u("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function Pb(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.Cc.Nc)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.Cc.Nc(a,b,c);a.Pd=[]}
function Qb(){I||(I=function(a,b){this.node=b;this.Kd=function(c){this.Ic=c};this.Kd(a);this.message="FS error"},I.prototype=Error(),I.prototype.constructor=I,[44].forEach(function(a){pb[a]=new I(a);pb[a].stack="<generic error, no stack>"}))}var Rb;function Sb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Tb(a,b,c){a=db("/dev/"+a);var d=Sb(!!b,!!c);Ub||(Ub=64);var e=Ub++<<8|0;jb(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,n,p){for(var t=0,y=0;y<p;y++){try{var D=b()}catch(S){throw new I(29);}if(void 0===D&&0===t)throw new I(6);if(null===D||void 0===D)break;t++;h[n+y]=D}t&&(f.node.timestamp=Date.now());return t},write:function(f,h,n,p){for(var t=0;t<p;t++)try{c(h[n+t])}catch(y){throw new I(29);}p&&(f.node.timestamp=Date.now());return t}});
Lb(a,d,e)}var Ub,N={},Ib,Ob,Vb={},Wb=void 0;function Xb(){Wb+=4;return x[Wb-4>>2]}function Yb(a){a=tb[a];if(!a)throw new I(8);return a}var Zb;fa?Zb=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?Zb=dateNow:Zb=function(){return performance.now()};function $b(){for(var a=O.length-1;0<=a;--a)ac(a);O=[];bc=[]}var bc=[];function cc(){if(dc.ud&&ec.dd)for(var a=0;a<bc.length;++a){var b=bc[a];bc.splice(a,1);--a;b.de.apply(null,b.Qd)}}var O=[];
function ac(a){var b=O[a];b.target.removeEventListener(b.Mc,b.Cd,b.Uc);O.splice(a,1)}function fc(a){function b(d){++dc.ud;ec=a;cc();a.Xc(d);cc();--dc.ud}if(a.Wc)a.Cd=b,a.target.addEventListener(a.Mc,b,a.Uc),O.push(a),hc||(Ha.push($b),hc=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].Mc==a.Mc&&ac(c--)}var dc={},hc,ec,ic,jc,kc,lc,mc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function P(a){a=2<a?C(a):a;return mc[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function nc(a){return 0>mc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function oc(a,b,c,d,e,f){ic||(ic=w(164));a={target:P(a),dd:!0,Mc:f,Wc:d,Xc:function(h){var n=ic,p=n>>2;x[p]=h.location;x[p+1]=h.ctrlKey;x[p+2]=h.shiftKey;x[p+3]=h.altKey;x[p+4]=h.metaKey;x[p+5]=h.repeat;x[p+6]=h.charCode;x[p+7]=h.keyCode;x[p+8]=h.which;E(h.key||"",B,n+36,32);E(h.code||"",B,n+68,32);E(h.char||"",B,n+100,32);E(h.locale||"",B,n+132,32);pc(d,e,n,b)&&h.preventDefault()},Uc:c};fc(a)}
function qc(a,b,c){a>>=2;x[a]=b.screenX;x[a+1]=b.screenY;x[a+2]=b.clientX;x[a+3]=b.clientY;x[a+4]=b.ctrlKey;x[a+5]=b.shiftKey;x[a+6]=b.altKey;x[a+7]=b.metaKey;za[2*a+16]=b.button;za[2*a+17]=b.buttons;x[a+9]=b.movementX;x[a+10]=b.movementY;c=nc(c);x[a+11]=b.clientX-c.left;x[a+12]=b.clientY-c.top}function rc(a,b,c,d,e,f){jc||(jc=w(64));a=P(a);fc({target:a,dd:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Mc:f,Wc:d,Xc:function(h){h=h||event;qc(jc,h,a);pc(d,e,jc,b)&&h.preventDefault()},Uc:c})}
function sc(a,b,c,d){kc||(kc=w(36));a=P(a);fc({target:a,Mc:"resize",Wc:d,Xc:function(e){e=e||event;if(e.target==a){var f=kc,h=document.body;x[f>>2]=e.detail;x[f+4>>2]=h.clientWidth;x[f+8>>2]=h.clientHeight;x[f+12>>2]=innerWidth;x[f+16>>2]=innerHeight;x[f+20>>2]=outerWidth;x[f+24>>2]=outerHeight;x[f+28>>2]=pageXOffset;x[f+32>>2]=pageYOffset;pc(d,10,f,b)&&e.preventDefault()}},Uc:c})}
function tc(a,b,c,d){lc||(lc=w(96));fc({target:a,dd:!0,Mc:"wheel",Wc:d,Xc:function(e){e=e||event;var f=lc;qc(f,e,a);Ba[f+64>>3]=e.deltaX;Ba[f+72>>3]=e.deltaY;Ba[f+80>>3]=e.deltaZ;x[f+88>>2]=e.deltaMode;pc(d,9,f,b)&&e.preventDefault()},Uc:c})}
function uc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function vc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function wc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var xc=1,yc=[],Q=[],zc=[],Ac=[],Bc=[],R=[],T=[],Cc=[],U=[],Dc=[],Ec=[],Fc={},Hc={},Ic={},Jc=4;function V(a){Kc||(Kc=a)}function Lc(a){for(var b=xc++,c=a.length;c<b;c++)a[c]=null;return b}
function Mc(a){a||(a=W);if(!a.Fd){a.Fd=!0;var b=a.Oc;uc(b);vc(b);wc(b);b.Sd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Td=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var W,Kc,Nc=["default","low-power","high-performance"];g._emscripten_webgl_get_current_context=function(){return W?W.Ed:0};function Oc(a){W=U[a];g.Rd=X=W&&W.Oc;return!a||X?0:-5}g._emscripten_webgl_make_context_current=Oc;var Pc={};
function Qc(){if(!Rc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Pc)a[b]=Pc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Rc=c}return Rc}var Rc,Sc=[];function Tc(a,b,c,d){for(var e=0;e<a;e++){var f=X[c](),h=f&&Lc(d);f?(f.name=h,d[h]=f):V(1282);x[b+4*e>>2]=h}}
function Uc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&V(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=X.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>W.version){V(1282);return}d=2*(X.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>W.version){V(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=X.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":V(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:V(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:G[b+4*a>>2]=e[a];break;case 4:A[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){V(1280);
u("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:V(1280);u("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=d;F[b>>2]=c;F[b+4>>2]=(c-F[b>>2])/4294967296;break;case 0:x[b>>2]=d;break;case 2:G[b>>2]=d;break;case 4:A[b>>0]=d?1:0}}else V(1281)}function Vc(a){var b=va(a)+1,c=w(b);E(a,B,c,b);return c}
function Wc(a){a-=5120;return 0==a?A:1==a?B:2==a?za:4==a?x:6==a?G:5==a||28922==a||28520==a||30779==a||30782==a?F:Aa}function Xc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Yc(a,b,c,d,e){a=Wc(a);var f=Xc(a),h=Jc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var Y=[],Zc=[];function $c(a){return 0===a%4&&(0!==a%100||0===a%400)}function ad(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var bd=[31,29,31,30,31,30,31,31,30,31,30,31],cd=[31,28,31,30,31,30,31,31,30,31,30,31];function dd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=($c(a.getFullYear())?bd:cd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function ed(a,b,c,d){function e(m,v,z){for(m="number"===typeof m?m.toString():m||"";m.length<v;)m=z[0]+m;return m}function f(m,v){return e(m,v,"0")}function h(m,v){function z(Gc){return 0>Gc?-1:0<Gc?1:0}var J;0===(J=z(m.getFullYear()-v.getFullYear()))&&0===(J=z(m.getMonth()-v.getMonth()))&&(J=z(m.getDate()-v.getDate()));return J}function n(m){switch(m.getDay()){case 0:return new Date(m.getFullYear()-1,11,29);case 1:return m;case 2:return new Date(m.getFullYear(),0,3);case 3:return new Date(m.getFullYear(),
0,2);case 4:return new Date(m.getFullYear(),0,1);case 5:return new Date(m.getFullYear()-1,11,31);case 6:return new Date(m.getFullYear()-1,11,30)}}function p(m){m=dd(new Date(m.Fc+1900,0,1),m.cd);var v=new Date(m.getFullYear()+1,0,4),z=n(new Date(m.getFullYear(),0,4));v=n(v);return 0>=h(z,m)?0>=h(v,m)?m.getFullYear()+1:m.getFullYear():m.getFullYear()-1}var t=x[d+40>>2];d={Nd:x[d>>2],Md:x[d+4>>2],ad:x[d+8>>2],Tc:x[d+12>>2],Qc:x[d+16>>2],Fc:x[d+20>>2],bd:x[d+24>>2],cd:x[d+28>>2],ee:x[d+32>>2],Ld:x[d+
36>>2],Od:t?C(t):""};c=C(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var y in t)c=c.replace(new RegExp(y,"g"),t[y]);var D="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
S="January February March April May June July August September October November December".split(" ");t={"%a":function(m){return D[m.bd].substring(0,3)},"%A":function(m){return D[m.bd]},"%b":function(m){return S[m.Qc].substring(0,3)},"%B":function(m){return S[m.Qc]},"%C":function(m){return f((m.Fc+1900)/100|0,2)},"%d":function(m){return f(m.Tc,2)},"%e":function(m){return e(m.Tc,2," ")},"%g":function(m){return p(m).toString().substring(2)},"%G":function(m){return p(m)},"%H":function(m){return f(m.ad,
2)},"%I":function(m){m=m.ad;0==m?m=12:12<m&&(m-=12);return f(m,2)},"%j":function(m){return f(m.Tc+ad($c(m.Fc+1900)?bd:cd,m.Qc-1),3)},"%m":function(m){return f(m.Qc+1,2)},"%M":function(m){return f(m.Md,2)},"%n":function(){return"\n"},"%p":function(m){return 0<=m.ad&&12>m.ad?"AM":"PM"},"%S":function(m){return f(m.Nd,2)},"%t":function(){return"\t"},"%u":function(m){return m.bd||7},"%U":function(m){var v=new Date(m.Fc+1900,0,1),z=0===v.getDay()?v:dd(v,7-v.getDay());m=new Date(m.Fc+1900,m.Qc,m.Tc);return 0>
h(z,m)?f(Math.ceil((31-z.getDate()+(ad($c(m.getFullYear())?bd:cd,m.getMonth()-1)-31)+m.getDate())/7),2):0===h(z,v)?"01":"00"},"%V":function(m){var v=new Date(m.Fc+1901,0,4),z=n(new Date(m.Fc+1900,0,4));v=n(v);var J=dd(new Date(m.Fc+1900,0,1),m.cd);return 0>h(J,z)?"53":0>=h(v,J)?"01":f(Math.ceil((z.getFullYear()<m.Fc+1900?m.cd+32-z.getDate():m.cd+1-z.getDate())/7),2)},"%w":function(m){return m.bd},"%W":function(m){var v=new Date(m.Fc,0,1),z=1===v.getDay()?v:dd(v,0===v.getDay()?1:7-v.getDay()+1);m=
new Date(m.Fc+1900,m.Qc,m.Tc);return 0>h(z,m)?f(Math.ceil((31-z.getDate()+(ad($c(m.getFullYear())?bd:cd,m.getMonth()-1)-31)+m.getDate())/7),2):0===h(z,v)?"01":"00"},"%y":function(m){return(m.Fc+1900).toString().substring(2)},"%Y":function(m){return m.Fc+1900},"%z":function(m){m=m.Ld;var v=0<=m;m=Math.abs(m)/60;return(v?"+":"-")+String("0000"+(m/60*100+m%60)).slice(-4)},"%Z":function(m){return m.Od},"%%":function(){return"%"}};for(y in t)0<=c.indexOf(y)&&(c=c.replace(new RegExp(y,"g"),t[y](d)));y=
Za(c,!1);if(y.length>b)return 0;A.set(y,a);return y.length-1}var fd=[];function Cb(a,b,c,d){a||(a=this);this.parent=a;this.Jc=a.Jc;this.Zc=null;this.id=ub++;this.name=b;this.mode=c;this.Dc={};this.Cc={};this.rdev=d}Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Qb();vb=Array(4096);Jb(K,"/");M("/tmp");M("/home");
M("/home/web_user");
(function(){M("/dev");jb(259,{read:function(){return 0},write:function(d,e,f,h){return h}});Lb("/dev/null",259);ib(1280,lb);ib(1536,mb);Lb("/dev/tty",1280);Lb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(fa)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){r("random_device")});Tb("random",b);Tb("urandom",b);M("/dev/shm");
M("/dev/shm/tmp")})();M("/proc");M("/proc/self");M("/proc/self/fd");Jb({Jc:function(){var a=ob("/proc/self","fd",16895,73);a.Dc={lookup:function(b,c){var d=tb[+c];if(!d)throw new I(8);b={parent:null,Jc:{xd:"fake"},Dc:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var X,Z=0;32>Z;++Z)Sc.push(Array(Z));var gd=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=gd.subarray(0,Z+1);var hd=new Int32Array(288);for(Z=0;288>Z;++Z)Zc[Z]=hd.subarray(0,Z+1);
function Za(a,b){var c=Array(va(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var ld={Sb:function(a){return w(a)},Qa:function(a){"uncaught_exception"in bb?bb.Vc++:bb.Vc=1;throw a;},ab:function(){x[id()>>2]=63;return-1},ib:function(a,b){try{a=C(a);if(b&-8)var c=-28;else{var d;(d=L(a,{hd:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&Bb(d,a)?-2:0):c=-44}return c}catch(e){return"undefined"!==typeof N&&e instanceof I||r(e),-e.Ic}},q:function(a,b,c){Wb=c;try{var d=Yb(a);switch(b){case 0:var e=Xb();return 0>e?-28:Nb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;
case 3:return d.flags;case 4:return e=Xb(),d.flags|=e,0;case 12:return e=Xb(),za[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return x[id()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof N&&f instanceof I||r(f),-f.Ic}},fb:function(a,b,c){Wb=c;try{var d=Yb(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Xb();return x[e>>2]=0;case 21520:return d.tty?
-28:-59;case 21531:a=e=Xb();if(!d.Cc.Gd)throw new I(59);return d.Cc.Gd(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:r("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof N&&f instanceof I||r(f),-f.Ic}},$a:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Vb[a];if(d&&b===d.Wd){var e=tb[d.fd];if(d.$d&2){var f=d.flags,h=d.offset,n=B.slice(a,a+b);e&&e.Cc.$c&&e.Cc.$c(e,n,h,b,f)}Vb[a]=null;d.Ad&&jd(d.Xd)}c=0}return c}catch(p){return"undefined"!==typeof N&&
p instanceof I||r(p),-p.Ic}},hb:function(a,b,c){Wb=c;try{var d=C(a),e=Xb();return Nb(d,b,e).fd}catch(f){return"undefined"!==typeof N&&f instanceof I||r(f),-f.Ic}},a:function(){r()},bb:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Zb();else return x[id()>>2]=28,-1;x[b>>2]=a/1E3|0;x[b+4>>2]=a%1E3*1E6|0;return 0},f:function(a,b,c){fd.length=0;var d;for(c>>=2;d=B[b++];)fd.push(105>d?Ba[++c>>1]:x[c]),++c;return $a[a].apply(null,fd)},Ta:function(a,b,c){a=P(a);if(!a)return-4;x[b>>2]=a.width;
x[c>>2]=a.height},Ia:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},Ua:function(a,b,c){a=P(a);if(!a)return-4;a=nc(a);Ba[b>>3]=a.width;Ba[c>>3]=a.height;return 0},Ya:function(a,b,c){B.copyWithin(a,b,b+c)},Za:function(){r("OOM")},n:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},gb:function(a,b,c,d){oc(a,b,c,d,2,"keydown");return 0},Xa:function(a,b,c,d){oc(a,b,c,d,3,"keyup");return 0},Rb:function(a,b,c,d){rc(a,b,c,d,5,"mousedown");return 0},yb:function(a,
b,c,d){rc(a,b,c,d,8,"mousemove");return 0},Ib:function(a,b,c,d){rc(a,b,c,d,6,"mouseup");return 0},F:function(a,b,c,d){sc(a,b,c,d);return 0},ob:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(tc(a,b,c,d),0):-1},Sa:function(){return W&&W.Oc&&W.attributes.rd?0:-3},_:function(a,b){var c={};b>>=2;c.alpha=!!x[b];c.depth=!!x[b+1];c.stencil=!!x[b+2];c.antialias=!!x[b+3];c.premultipliedAlpha=!!x[b+4];c.preserveDrawingBuffer=!!x[b+5];c.powerPreference=Nc[x[b+6]];c.failIfMajorPerformanceCaveat=
!!x[b+7];c.vd=x[b+8];c.Yd=x[b+9];c.pd=x[b+10];c.rd=x[b+11];c.ae=x[b+12];c.ce=x[b+13];if(a=P(a))if(c.rd)c=-1;else if(a=1<c.vd?a.getContext("webgl2",c):a.getContext("webgl",c)){b=Lc(U);var d={Ed:b,attributes:c,version:c.vd,Oc:a};a.canvas&&(a.canvas.zd=d);U[b]=d;("undefined"===typeof c.pd||c.pd)&&Mc(d);c=b}else c=0;else c=-4;return c},za:function(a){W==a&&(W=0);W===U[a]&&(W=null);if("object"===typeof dc)for(var b=U[a].Oc.canvas,c=0;c<O.length;++c)O[c].target!=b||ac(c--);U[a]&&U[a].Oc.canvas&&(U[a].Oc.canvas.zd=
void 0);U[a]=null},ia:function(a){a>>=2;for(var b=0;14>b;++b)x[a+b]=0;x[a]=x[a+1]=x[a+3]=x[a+4]=x[a+8]=x[a+10]=1},Q:Oc,cb:function(a,b){var c=0;Qc().forEach(function(d,e){var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)A[e++>>0]=d.charCodeAt(f);A[e>>0]=0;c+=d.length+1});return 0},db:function(a,b){var c=Qc();x[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});x[b>>2]=d;return 0},h:function(a){kd(a)},s:function(a){try{var b=Yb(a);if(null===b.fd)throw new I(8);b.jd&&(b.jd=null);try{b.Cc.close&&
b.Cc.close(b)}catch(c){throw c;}finally{tb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof N&&c instanceof I||r(c),c.Ic}},eb:function(a,b,c,d){try{a:{for(var e=Yb(a),f=a=0;f<c;f++){var h=x[b+(8*f+4)>>2],n=e,p=x[b+8*f>>2],t=h,y=void 0,D=A;if(0>t||0>y)throw new I(28);if(null===n.fd)throw new I(8);if(1===(n.flags&2097155))throw new I(8);if(16384===(n.node.mode&61440))throw new I(31);if(!n.Cc.read)throw new I(28);var S="undefined"!==typeof y;if(!S)y=n.position;else if(!n.seekable)throw new I(70);
var m=n.Cc.read(n,D,p,t,y);S||(n.position+=m);var v=m;if(0>v){var z=-1;break a}a+=v;if(v<h)break}z=a}x[d>>2]=z;return 0}catch(J){return"undefined"!==typeof N&&J instanceof I||r(J),J.Ic}},Va:function(a,b,c,d,e){try{var f=Yb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Pb(f,a,d);Ya=[f.position>>>0,(Xa=f.position,1<=+Ka(Xa)?0<Xa?(Na(+Ma(Xa/4294967296),4294967295)|0)>>>0:~~+La((Xa-+(~~Xa>>>0))/4294967296)>>>0:0)];x[e>>2]=Ya[0];x[e+4>>2]=Ya[1];f.jd&&0===a&&0===d&&(f.jd=
null);return 0}catch(h){return"undefined"!==typeof N&&h instanceof I||r(h),h.Ic}},r:function(a,b,c,d){try{a:{for(var e=Yb(a),f=a=0;f<c;f++){var h=e,n=x[b+8*f>>2],p=x[b+(8*f+4)>>2],t=void 0,y=A;if(0>p||0>t)throw new I(28);if(null===h.fd)throw new I(8);if(0===(h.flags&2097155))throw new I(8);if(16384===(h.node.mode&61440))throw new I(31);if(!h.Cc.write)throw new I(28);h.seekable&&h.flags&1024&&Pb(h,0,2);var D="undefined"!==typeof t;if(!D)t=h.position;else if(!h.seekable)throw new I(70);var S=h.Cc.write(h,
y,n,p,t,void 0);D||(h.position+=S);try{if(h.path&&xb.onWriteToFile)xb.onWriteToFile(h.path)}catch(z){u("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+z.message)}var m=S;if(0>m){var v=-1;break a}a+=m}v=a}x[d>>2]=v;return 0}catch(z){return"undefined"!==typeof N&&z instanceof I||r(z),z.Ic}},j:function(a){X.activeTexture(a)},N:function(a,b){X.attachShader(Q[a],T[b])},o:function(a,b){35051==a?X.gd=b:35052==a&&(X.Kc=b);X.bindBuffer(a,yc[b])},p:function(a,b,c){X.bindBufferBase(a,
b,yc[c])},Na:function(a,b,c,d,e){X.bindBufferRange(a,b,yc[c],d,e)},l:function(a,b){X.bindFramebuffer(a,zc[b])},xa:function(a,b){X.bindRenderbuffer(a,Ac[b])},i:function(a,b){X.bindTexture(a,Bc[b])},ha:function(a,b){X.bindTransformFeedback(a,Ec[b])},qb:function(a){X.bindVertexArray(Cc[a])},ra:function(a,b){X.blendFunc(a,b)},fa:function(a,b,c,d,e,f,h,n,p,t){X.blitFramebuffer(a,b,c,d,e,f,h,n,p,t)},Ka:function(a,b,c,d){2<=W.version?c?X.bufferData(a,B,d,c,b):X.bufferData(a,b,d):X.bufferData(a,c?B.subarray(c,
c+b):b,d)},Ja:function(a,b,c,d){2<=W.version?X.bufferSubData(a,b,B,d,c):X.bufferSubData(a,b,B.subarray(d,d+c))},ba:function(a){return X.checkFramebufferStatus(a)},ea:function(a){X.clear(a)},Y:function(a,b,c,d){X.clearBufferfi(a,b,c,d)},Z:function(a,b,c){X.clearBufferfv(a,b,G,c>>2)},aa:function(a,b,c){X.clearBufferiv(a,b,x,c>>2)},$:function(a,b,c){X.clearBufferuiv(a,b,F,c>>2)},ta:function(a,b,c,d){X.clearColor(a,b,c,d)},qa:function(a){X.clearDepth(a)},ma:function(a){X.compileShader(T[a])},t:function(a,
b,c,d,e,f,h,n,p){2<=W.version?X.Kc?X.compressedTexSubImage2D(a,b,c,d,e,f,h,n,p):X.compressedTexSubImage2D(a,b,c,d,e,f,h,B,p,n):X.compressedTexSubImage2D(a,b,c,d,e,f,h,p?B.subarray(p,p+n):null)},vb:function(a,b,c,d,e,f,h,n,p,t,y){X.Kc?X.compressedTexSubImage3D(a,b,c,d,e,f,h,n,p,t,y):X.compressedTexSubImage3D(a,b,c,d,e,f,h,n,p,B,y,t)},Ma:function(a,b,c,d,e){X.copyBufferSubData(a,b,c,d,e)},U:function(a,b,c,d,e,f,h,n){X.copyTexSubImage2D(a,b,c,d,e,f,h,n)},T:function(a,b,c,d,e,f,h,n,p){X.copyTexSubImage3D(a,
b,c,d,e,f,h,n,p)},S:function(){var a=Lc(Q),b=X.createProgram();b.name=a;Q[a]=b;return a},pa:function(a){var b=Lc(T);T[b]=X.createShader(a);return b},Oa:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=yc[d];e&&(X.deleteBuffer(e),e.name=0,yc[d]=null,d==X.gd&&(X.gd=0),d==X.Kc&&(X.Kc=0))}},Ea:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=zc[d];e&&(X.deleteFramebuffer(e),e.name=0,zc[d]=null)}},R:function(a){if(a){var b=Q[a];b?(X.deleteProgram(b),b.name=0,Q[a]=null,Fc[a]=null):V(1281)}},
ya:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Ac[d];e&&(X.deleteRenderbuffer(e),e.name=0,Ac[d]=null)}},oa:function(a){if(a){var b=T[a];b?(X.deleteShader(b),T[a]=null):V(1281)}},Hb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Bc[d];e&&(X.deleteTexture(e),e.name=0,Bc[d]=null)}},nb:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];X.deleteVertexArray(Cc[d]);Cc[d]=null}},d:function(a){X.disable(a)},ub:function(a,b,c){X.drawArrays(a,b,c)},sb:function(a,b,c,d){X.drawArraysInstanced(a,
b,c,d)},X:function(a,b){for(var c=Sc[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];X.drawBuffers(c)},tb:function(a,b,c,d){X.drawElements(a,b,c,d)},rb:function(a,b,c,d,e){X.drawElementsInstanced(a,b,c,d,e)},c:function(a){X.enable(a)},mb:function(a){X.enableVertexAttribArray(a)},Da:function(a,b,c,d){X.framebufferRenderbuffer(a,b,c,Ac[d])},Ca:function(a,b,c,d,e){X.framebufferTexture2D(a,b,c,Bc[d],e)},Ba:function(a,b,c,d,e){X.framebufferTextureLayer(a,b,Bc[c],d,e)},Pa:function(a,b){Tc(a,b,"createBuffer",yc)},Fa:function(a,
b){Tc(a,b,"createFramebuffer",zc)},ka:function(a,b){Tc(a,b,"createQuery",Dc)},Aa:function(a,b){Tc(a,b,"createRenderbuffer",Ac)},Jb:function(a,b){Tc(a,b,"createTexture",Bc)},ja:function(a,b){Tc(a,b,"createTransformFeedback",Ec)},pb:function(a,b){Tc(a,b,"createVertexArray",Cc)},Gb:function(a){X.generateMipmap(a)},La:function(a,b,c){c?x[c>>2]=X.getBufferParameter(a,b):V(1281)},Ha:function(){var a=X.getError()||Kc;Kc=0;return a},ua:function(a,b){Uc(a,b,2)},e:function(a,b){Uc(a,b,0)},P:function(a,b,c,
d){a=X.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,B,d,b):0;c&&(x[c>>2]=b)},k:function(a,b,c){if(c)if(a>=xc)V(1281);else{var d=Fc[a];if(d)if(35716==b)a=X.getProgramInfoLog(Q[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.kd;else if(35722==b){if(-1==d.Rc){a=Q[a];var e=X.getProgramParameter(a,35721);for(b=d.Rc=0;b<e;++b)d.Rc=Math.max(d.Rc,X.getActiveAttrib(a,b).name.length+1)}x[c>>2]=d.Rc}else if(35381==b){if(-1==d.Sc)for(a=Q[a],e=X.getProgramParameter(a,
35382),b=d.Sc=0;b<e;++b)d.Sc=Math.max(d.Sc,X.getActiveUniformBlockName(a,b).length+1);x[c>>2]=d.Sc}else x[c>>2]=X.getProgramParameter(Q[a],b);else V(1282)}else V(1281)},la:function(a,b,c,d){a=X.getShaderInfoLog(T[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,B,d,b):0;c&&(x[c>>2]=b)},m:function(a,b,c){c?35716==b?(a=X.getShaderInfoLog(T[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1):35720==b?(a=X.getShaderSource(T[a]),x[c>>2]=null===a||0==a.length?0:a.length+1):x[c>>2]=X.getShaderParameter(T[a],
b):V(1281)},g:function(a){if(Hc[a])return Hc[a];switch(a){case 7939:var b=X.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Vc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||V(1280);b=Vc(b);break;case 7938:b=X.getParameter(7938);b=2<=W.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Vc(b);break;case 35724:b=X.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+=
"0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Vc(b);break;default:return V(1280),0}return Hc[a]=b},Ga:function(a,b){if(2>W.version)return V(1282),0;var c=Ic[a];if(c)return 0>b||b>=c.length?(V(1281),0):c[b];switch(a){case 7939:return c=X.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Vc(d)}),c=Ic[a]=c,0>b||b>=c.length?(V(1281),0):c[b];default:return V(1280),0}},K:function(a,b){b=C(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=
b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=Fc[a]&&Fc[a].yd[b])&&0<=c&&c<a[0]?a[1]+c:-1},da:function(a,b,c){for(var d=Sc[b],e=0;e<b;e++)d[e]=x[c+4*e>>2];X.invalidateFramebuffer(a,d)},ca:function(a,b,c,d,e,f,h){for(var n=Sc[b],p=0;p<b;p++)n[p]=x[c+4*p>>2];X.invalidateSubFramebuffer(a,n,d,e,f,h)},L:function(a){X.linkProgram(Q[a]);var b=Q[a];a=Fc[a]={yd:{},kd:0,Rc:-1,Sc:-1};for(var c=a.yd,d=X.getProgramParameter(b,35718),e=0;e<d;++e){var f=X.getActiveUniform(b,e),h=f.name;a.kd=Math.max(a.kd,
h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var n=X.getUniformLocation(b,h);if(n){var p=Lc(R);c[h]=[f.size,p];R[p]=n;for(var t=1;t<f.size;++t)n=X.getUniformLocation(b,h+"["+t+"]"),p=Lc(R),R[p]=n}}},b:function(a,b){3317==a&&(Jc=b);X.pixelStorei(a,b)},W:function(a){X.readBuffer(a)},V:function(a,b,c,d,e,f,h){if(2<=W.version)if(X.gd)X.readPixels(a,b,c,d,e,f,h);else{var n=Wc(f);X.readPixels(a,b,c,d,e,f,n,h>>Xc(n))}else(h=Yc(f,e,c,d,h))?X.readPixels(a,b,c,d,e,f,h):V(1280)},wa:function(a,
b,c,d){X.renderbufferStorage(a,b,c,d)},va:function(a,b,c,d,e){X.renderbufferStorageMultisample(a,b,c,d,e)},sa:function(a,b,c,d){X.scissor(a,b,c,d)},na:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?x[d+4*f>>2]:-1;e+=C(x[c+4*f>>2],0>h?void 0:h)}X.shaderSource(T[a],e)},zb:function(a,b,c,d,e,f,h,n,p){if(2<=W.version)if(X.Kc)X.texImage2D(a,b,c,d,e,f,h,n,p);else if(p){var t=Wc(n);X.texImage2D(a,b,c,d,e,f,h,n,t,p>>Xc(t))}else X.texImage2D(a,b,c,d,e,f,h,n,null);else X.texImage2D(a,b,c,d,e,f,h,n,p?Yc(n,
h,d,e,p):null)},xb:function(a,b,c,d,e,f,h,n,p,t){if(X.Kc)X.texImage3D(a,b,c,d,e,f,h,n,p,t);else if(t){var y=Wc(p);X.texImage3D(a,b,c,d,e,f,h,n,p,y,t>>Xc(y))}else X.texImage3D(a,b,c,d,e,f,h,n,p,null)},Eb:function(a,b,c){X.texParameterf(a,b,c)},Cb:function(a,b,c){X.texParameterf(a,b,G[c>>2])},Fb:function(a,b,c){X.texParameteri(a,b,c)},Db:function(a,b,c){X.texParameteri(a,b,x[c>>2])},Bb:function(a,b,c,d,e){X.texStorage2D(a,b,c,d,e)},Ab:function(a,b,c,d,e,f){X.texStorage3D(a,b,c,d,e,f)},u:function(a,
b,c,d,e,f,h,n,p){if(2<=W.version)if(X.Kc)X.texSubImage2D(a,b,c,d,e,f,h,n,p);else if(p){var t=Wc(n);X.texSubImage2D(a,b,c,d,e,f,h,n,t,p>>Xc(t))}else X.texSubImage2D(a,b,c,d,e,f,h,n,null);else t=null,p&&(t=Yc(n,h,e,f,p)),X.texSubImage2D(a,b,c,d,e,f,h,n,t)},wb:function(a,b,c,d,e,f,h,n,p,t,y){if(X.Kc)X.texSubImage3D(a,b,c,d,e,f,h,n,p,t,y);else if(y){var D=Wc(t);X.texSubImage3D(a,b,c,d,e,f,h,n,p,t,D,y>>Xc(D))}else X.texSubImage3D(a,b,c,d,e,f,h,n,p,t,null)},M:function(a,b,c,d){a=Q[a];for(var e=[],f=0;f<
b;f++)e.push(C(x[c+4*f>>2]));X.transformFeedbackVaryings(a,e,d)},J:function(a,b,c){if(2<=W.version)X.uniform1fv(R[a],G,c>>2,b);else{if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=G[c+4*e>>2];else d=G.subarray(c>>2,c+4*b>>2);X.uniform1fv(R[a],d)}},E:function(a,b,c){if(2<=W.version)X.uniform1iv(R[a],x,c>>2,b);else{if(288>=b)for(var d=Zc[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);X.uniform1iv(R[a],d)}},A:function(a,b,c){X.uniform1uiv(R[a],F,c>>2,b)},I:function(a,b,c){if(2<=W.version)X.uniform2fv(R[a],
G,c>>2,2*b);else{if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=G[c+4*e>>2],d[e+1]=G[c+(4*e+4)>>2];else d=G.subarray(c>>2,c+8*b>>2);X.uniform2fv(R[a],d)}},D:function(a,b,c){if(2<=W.version)X.uniform2iv(R[a],x,c>>2,2*b);else{if(144>=b)for(var d=Zc[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);X.uniform2iv(R[a],d)}},z:function(a,b,c){X.uniform2uiv(R[a],F,c>>2,2*b)},H:function(a,b,c){if(2<=W.version)X.uniform3fv(R[a],G,c>>2,3*b);else{if(96>=b)for(var d=
Y[3*b-1],e=0;e<3*b;e+=3)d[e]=G[c+4*e>>2],d[e+1]=G[c+(4*e+4)>>2],d[e+2]=G[c+(4*e+8)>>2];else d=G.subarray(c>>2,c+12*b>>2);X.uniform3fv(R[a],d)}},C:function(a,b,c){if(2<=W.version)X.uniform3iv(R[a],x,c>>2,3*b);else{if(96>=b)for(var d=Zc[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);X.uniform3iv(R[a],d)}},y:function(a,b,c){X.uniform3uiv(R[a],F,c>>2,3*b)},G:function(a,b,c){if(2<=W.version)X.uniform4fv(R[a],G,c>>2,4*b);else{if(72>=
b){var d=Y[4*b-1];c>>=2;for(var e=0;e<4*b;e+=4){var f=c+e;d[e]=G[f];d[e+1]=G[f+1];d[e+2]=G[f+2];d[e+3]=G[f+3]}}else d=G.subarray(c>>2,c+16*b>>2);X.uniform4fv(R[a],d)}},B:function(a,b,c){if(2<=W.version)X.uniform4iv(R[a],x,c>>2,4*b);else{if(72>=b)for(var d=Zc[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);X.uniform4iv(R[a],d)}},x:function(a,b,c){X.uniform4uiv(R[a],F,c>>2,4*b)},w:function(a,b,c,d){if(2<=
W.version)X.uniformMatrix2fv(R[a],!!c,G,d>>2,4*b);else{if(72>=b)for(var e=Y[4*b-1],f=0;f<4*b;f+=4)e[f]=G[d+4*f>>2],e[f+1]=G[d+(4*f+4)>>2],e[f+2]=G[d+(4*f+8)>>2],e[f+3]=G[d+(4*f+12)>>2];else e=G.subarray(d>>2,d+16*b>>2);X.uniformMatrix2fv(R[a],!!c,e)}},Pb:function(a,b,c,d){X.uniformMatrix2x3fv(R[a],!!c,G,d>>2,6*b)},Nb:function(a,b,c,d){X.uniformMatrix2x4fv(R[a],!!c,G,d>>2,8*b)},v:function(a,b,c,d){if(2<=W.version)X.uniformMatrix3fv(R[a],!!c,G,d>>2,9*b);else{if(32>=b)for(var e=Y[9*b-1],f=0;f<9*b;f+=
9)e[f]=G[d+4*f>>2],e[f+1]=G[d+(4*f+4)>>2],e[f+2]=G[d+(4*f+8)>>2],e[f+3]=G[d+(4*f+12)>>2],e[f+4]=G[d+(4*f+16)>>2],e[f+5]=G[d+(4*f+20)>>2],e[f+6]=G[d+(4*f+24)>>2],e[f+7]=G[d+(4*f+28)>>2],e[f+8]=G[d+(4*f+32)>>2];else e=G.subarray(d>>2,d+36*b>>2);X.uniformMatrix3fv(R[a],!!c,e)}},Ob:function(a,b,c,d){X.uniformMatrix3x2fv(R[a],!!c,G,d>>2,6*b)},Lb:function(a,b,c,d){X.uniformMatrix3x4fv(R[a],!!c,G,d>>2,12*b)},Qb:function(a,b,c,d){if(2<=W.version)X.uniformMatrix4fv(R[a],!!c,G,d>>2,16*b);else{if(18>=b){var e=
Y[16*b-1];d>>=2;for(var f=0;f<16*b;f+=16){var h=d+f;e[f]=G[h];e[f+1]=G[h+1];e[f+2]=G[h+2];e[f+3]=G[h+3];e[f+4]=G[h+4];e[f+5]=G[h+5];e[f+6]=G[h+6];e[f+7]=G[h+7];e[f+8]=G[h+8];e[f+9]=G[h+9];e[f+10]=G[h+10];e[f+11]=G[h+11];e[f+12]=G[h+12];e[f+13]=G[h+13];e[f+14]=G[h+14];e[f+15]=G[h+15]}}else e=G.subarray(d>>2,d+64*b>>2);X.uniformMatrix4fv(R[a],!!c,e)}},Mb:function(a,b,c,d){X.uniformMatrix4x2fv(R[a],!!c,G,d>>2,8*b)},Kb:function(a,b,c,d){X.uniformMatrix4x3fv(R[a],!!c,G,d>>2,12*b)},O:function(a){X.useProgram(Q[a])},
jb:function(a,b){X.vertexAttribDivisor(a,b)},lb:function(a,b,c,d,e){X.vertexAttribIPointer(a,b,c,d,e)},kb:function(a,b,c,d,e,f){X.vertexAttribPointer(a,b,c,!!d,e,f)},ga:function(a,b,c,d){X.viewport(a,b,c,d)},memory:pa,Ra:function(a){a=+a;return 0<=a?+Ma(a+.5):+La(a-.5)},Wa:function(){},_a:function(a,b,c,d){return ed(a,b,c,d)},table:qa};
(function(){function a(e){g.asm=e.exports;Oa--;g.monitorRunDependencies&&g.monitorRunDependencies(Oa);0==Oa&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa&&(e=Qa,Qa=null,e()))}function b(e){a(e.instance)}function c(e){return Wa().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){u("failed to asynchronously prepare wasm: "+f);r(f)})}var d={a:ld};Oa++;g.monitorRunDependencies&&g.monitorRunDependencies(Oa);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return u("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){if(oa||"function"!==typeof WebAssembly.instantiateStreaming||Ta()||Ra("file://")||"function"!==typeof fetch)return c(b);fetch(Sa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){u("wasm streaming compile failed: "+f);u("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var ab=g.___wasm_call_ctors=function(){return(ab=g.___wasm_call_ctors=g.asm.Tb).apply(null,arguments)};
g._main=function(){return(g._main=g.asm.Ub).apply(null,arguments)};var w=g._malloc=function(){return(w=g._malloc=g.asm.Vb).apply(null,arguments)},jd=g._free=function(){return(jd=g._free=g.asm.Wb).apply(null,arguments)},id=g.___errno_location=function(){return(id=g.___errno_location=g.asm.Xb).apply(null,arguments)},xa=g.stackAlloc=function(){return(xa=g.stackAlloc=g.asm.Yb).apply(null,arguments)};g.dynCall_vi=function(){return(g.dynCall_vi=g.asm.Zb).apply(null,arguments)};
g.dynCall_ii=function(){return(g.dynCall_ii=g.asm._b).apply(null,arguments)};g.dynCall_vii=function(){return(g.dynCall_vii=g.asm.$b).apply(null,arguments)};g.dynCall_v=function(){return(g.dynCall_v=g.asm.ac).apply(null,arguments)};g.dynCall_viiii=function(){return(g.dynCall_viiii=g.asm.bc).apply(null,arguments)};g.dynCall_vifi=function(){return(g.dynCall_vifi=g.asm.cc).apply(null,arguments)};g.dynCall_vif=function(){return(g.dynCall_vif=g.asm.dc).apply(null,arguments)};
g.dynCall_viii=function(){return(g.dynCall_viii=g.asm.ec).apply(null,arguments)};var pc=g.dynCall_iiii=function(){return(pc=g.dynCall_iiii=g.asm.fc).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.gc).apply(null,arguments)};g.dynCall_iii=function(){return(g.dynCall_iii=g.asm.hc).apply(null,arguments)};g.dynCall_viiiii=function(){return(g.dynCall_viiiii=g.asm.ic).apply(null,arguments)};g.dynCall_viifi=function(){return(g.dynCall_viifi=g.asm.jc).apply(null,arguments)};
g.dynCall_viiiiii=function(){return(g.dynCall_viiiiii=g.asm.kc).apply(null,arguments)};g.dynCall_vf=function(){return(g.dynCall_vf=g.asm.lc).apply(null,arguments)};g.dynCall_viiiiiiii=function(){return(g.dynCall_viiiiiiii=g.asm.mc).apply(null,arguments)};g.dynCall_viiiiiii=function(){return(g.dynCall_viiiiiii=g.asm.nc).apply(null,arguments)};g.dynCall_viif=function(){return(g.dynCall_viif=g.asm.oc).apply(null,arguments)};
g.dynCall_viiiiiiiii=function(){return(g.dynCall_viiiiiiiii=g.asm.pc).apply(null,arguments)};g.dynCall_iiiii=function(){return(g.dynCall_iiiii=g.asm.qc).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.rc).apply(null,arguments)};g.dynCall_iidiiii=function(){return(g.dynCall_iidiiii=g.asm.sc).apply(null,arguments)};g.dynCall_iiiiii=function(){return(g.dynCall_iiiiii=g.asm.tc).apply(null,arguments)};
g.dynCall_iiiiiiiii=function(){return(g.dynCall_iiiiiiiii=g.asm.uc).apply(null,arguments)};g.dynCall_iiiiiii=function(){return(g.dynCall_iiiiiii=g.asm.vc).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.wc).apply(null,arguments)};g.dynCall_iiiiid=function(){return(g.dynCall_iiiiid=g.asm.xc).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.yc).apply(null,arguments)};
g.dynCall_iiiiiiii=function(){return(g.dynCall_iiiiiiii=g.asm.zc).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Ac).apply(null,arguments)};var md;function ma(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Qa=function nd(){md||od();md||(Qa=nd)};
function od(a){function b(){if(!md&&(md=!0,g.calledRun=!0,!ra)){g.noFSInit||Rb||(Rb=!0,Qb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Tb("stdin",g.stdin):Mb("/dev/tty","/dev/stdin"),g.stdout?Tb("stdout",null,g.stdout):Mb("/dev/tty","/dev/stdout"),g.stderr?Tb("stderr",null,g.stderr):Mb("/dev/tty1","/dev/stderr"),Nb("/dev/stdin","r"),Nb("/dev/stdout","w"),Nb("/dev/stderr","w"));Da(Fa);wb=!1;Da(Ga);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(pd){var c=a,d=g._main;c=c||[];
var e=c.length+1,f=xa(4*(e+1));x[f>>2]=wa(ca);for(var h=1;h<e;h++)x[(f>>2)+h]=wa(c[h-1]);x[(f>>2)+e]=0;try{var n=d(e,f);kd(n,!0)}catch(p){p instanceof ma||("unwind"==p?noExitRuntime=!0:((c=p)&&"object"===typeof p&&p.stack&&(c=[p,p.stack]),u("exception thrown: "+c),da(1,p)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Ia.unshift(c);Da(Ia)}}a=a||ba;if(!(0<Oa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ja();
Da(Ea);0<Oa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=od;function kd(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime&&(ra=!0,g.onExit))g.onExit(a);da(a,new ma(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var pd=!0;g.noInitialRun&&(pd=!1);noExitRuntime=!0;od();
